name: PHP-Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v1 #https://github.com/shivammathur/setup-php
      with:
        php-version: 7.4
        extensions: mbstring, simplexml, dom
        coverage: xdebug #optional

    - name: Update composer
      run: composer update

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test
